version: '3.1'
networks:
  laravel:
    driver: bridge
services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=q1w2e3
            - MYSQL_DATABASE=dataseed
            - MYSQL_USER=alex
            - MYSQL_PASSWORD=q1w2e3
        ports:
            - '3306:3306'
        networks:
             - laravel

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '16000:80'
        networks:
             - laravel

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        networks:
             - laravel